services:
  mongodb:
    image: mongo:7
    container_name: vybe-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=vybe
    restart: unless-stopped

volumes:
  mongo_data:
